baseurl = "https://maloymanna.github.io/"
languageCode = "en-us"
title = "Maloy Manna"
theme = "blackburn"
author = "Maloy Manna"
copyright = "&copy; 2007 - 2025. All rights reserved."
#canonifyurls = true
ignoreFiles = ["\\.foo$", "\\.bak$", "\\.sh$"]
pagination.pagerSize = 5
buildFuture = "true"
enableEmoji = true
publishDir = "public"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  category = "categories"

[params]
  # Shown in the home page
  subtitle = "Data, Tech, Cloud Security & Agile Project Management"
  brand = "Maloy<br>Manna"
  # googleAnalytics = ""
  disqus = "maloymanna"
  # CSS name for highlight.js
  highlightjs = "github"
  dateFormat = "2006/01/02"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  # custom_css = ["css/capsule.min.css"]
  custom_css = ["css/theme-toggle.css"]
  custom_js  = ["js/theme-toggle.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Tech posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Categories"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 4
    identifier = "category"
    url = "/categories/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 5
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "Agile PM posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 6
    identifier = "pm"
    url = "/pm/"
  [[menu.main]]
    name = "Talks"
    pre = "<i class='fa fa-comments fa-fw'></i>"
    weight = 7
    identifier = "talk"
    url = "/talks/"          
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone-square fa-fw'></i>"
    weight = 8
    identifier = "contact"
    url = "/contact/"

[params.social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.
  linkedin = "maloy"
  twitter = "itsmaloy"
  github = "maloymanna"
  